// What the legacy SVGA3D names mean in Direct3D 9 terms: the D3D9 executor
// takes D3D9 enums. VMware designed SVGA3D's legacy commands after D3D9, so
// most of this is renumbering; the exceptions (cull mode and winding, fog
// mode, alpha reference, gamma, texture arguments) are noted where they are.

import * as C from "./svga_constants.js";
import { DX_FORMATS, AFTER_DX10 } from "./svga_dx_formats.js";

// D3DFORMAT values
const D3DFMT = {
    A8R8G8B8: 21, X8R8G8B8: 22, R5G6B5: 23, X1R5G5B5: 24, A1R5G5B5: 25, A4R4G4B4: 26,
    A8: 28, A2B10G10R10: 31, A8B8G8R8: 32, G16R16: 34, A2R10G10B10: 35, A16B16G16R16: 36,
    P8: 41, L8: 50, A8L8: 51, A4L4: 52, V8U8: 60, L6V5U5: 61, X8L8V8U8: 62, Q8W8V8U8: 63,
    V16U16: 64, A2W10V10U10: 67, D32: 71, D15S1: 73, D24S8: 75, D24X8: 77, D16: 80, L16: 81,
    D32F_LOCKABLE: 82, R16F: 111, G16R16F: 112, A16B16G16R16F: 113, R32F: 114, G32R32F: 115,
    A32B32G32R32F: 116, CxV8U8: 117,
    UYVY: 0x59565955, YUY2: 0x32595559,
    DXT1: 0x31545844, DXT2: 0x32545844, DXT3: 0x33545844, DXT4: 0x34545844, DXT5: 0x35545844,
    DF16: 0x36314644, DF24: 0x34324644, INTZ: 0x5A544E49, ATI1: 0x31495441, ATI2: 0x32495441,
    INDEX16: 101, INDEX32: 102,
};
export { D3DFMT };

/**
 * One surface format: its D3D9 format, its bytes per pixel or per 4x4 block,
 * and what it is good for
 * @typedef {{d3d: number, bytes: number, block: number, depth: boolean, target: boolean}}
 */
let FormatInfo;

/**
 * @param {number} d3d
 * @param {number} bytes
 * @param {Object=} extra
 * @return {FormatInfo}
 */
function f(d3d, bytes, extra)
{
    return /** @type {FormatInfo} */ (Object.assign({ d3d, bytes, block: 1, depth: false, target: false }, extra || {}));
}
const target = { target: true };
const depth = { depth: true };
const block = { block: 4 };

/** @type {!Object<number, FormatInfo>} SVGA3dSurfaceFormat -> */
export const FORMATS = {
    [C.SVGA3D_X8R8G8B8]: f(D3DFMT.X8R8G8B8, 4, target),
    [C.SVGA3D_A8R8G8B8]: f(D3DFMT.A8R8G8B8, 4, target),
    [C.SVGA3D_R5G6B5]: f(D3DFMT.R5G6B5, 2, target),
    [C.SVGA3D_X1R5G5B5]: f(D3DFMT.X1R5G5B5, 2, target),
    [C.SVGA3D_A1R5G5B5]: f(D3DFMT.A1R5G5B5, 2, target),
    [C.SVGA3D_A4R4G4B4]: f(D3DFMT.A4R4G4B4, 2),
    [C.SVGA3D_Z_D32]: f(D3DFMT.D32, 4, depth),
    [C.SVGA3D_Z_D16]: f(D3DFMT.D16, 2, depth),
    [C.SVGA3D_Z_D24S8]: f(D3DFMT.D24S8, 4, depth),
    [C.SVGA3D_Z_D15S1]: f(D3DFMT.D15S1, 2, depth),
    [C.SVGA3D_LUMINANCE8]: f(D3DFMT.L8, 1),
    [C.SVGA3D_LUMINANCE4_ALPHA4]: f(D3DFMT.A4L4, 1),
    [C.SVGA3D_LUMINANCE16]: f(D3DFMT.L16, 2),
    [C.SVGA3D_LUMINANCE8_ALPHA8]: f(D3DFMT.A8L8, 2),
    [C.SVGA3D_DXT1]: f(D3DFMT.DXT1, 8, block),
    [C.SVGA3D_DXT2]: f(D3DFMT.DXT2, 16, block),
    [C.SVGA3D_DXT3]: f(D3DFMT.DXT3, 16, block),
    [C.SVGA3D_DXT4]: f(D3DFMT.DXT4, 16, block),
    [C.SVGA3D_DXT5]: f(D3DFMT.DXT5, 16, block),
    [C.SVGA3D_BUMPU8V8]: f(D3DFMT.V8U8, 2),
    [C.SVGA3D_BUMPL6V5U5]: f(D3DFMT.L6V5U5, 2),
    [C.SVGA3D_BUMPX8L8V8U8]: f(D3DFMT.X8L8V8U8, 4),
    [C.SVGA3D_ARGB_S10E5]: f(D3DFMT.A16B16G16R16F, 8, target),
    [C.SVGA3D_ARGB_S23E8]: f(D3DFMT.A32B32G32R32F, 16, target),
    [C.SVGA3D_A2R10G10B10]: f(D3DFMT.A2R10G10B10, 4, target),
    [C.SVGA3D_V8U8]: f(D3DFMT.V8U8, 2),
    [C.SVGA3D_Q8W8V8U8]: f(D3DFMT.Q8W8V8U8, 4),
    [C.SVGA3D_CxV8U8]: f(D3DFMT.CxV8U8, 2),
    [C.SVGA3D_X8L8V8U8]: f(D3DFMT.X8L8V8U8, 4),
    [C.SVGA3D_A2W10V10U10]: f(D3DFMT.A2W10V10U10, 4),
    [C.SVGA3D_ALPHA8]: f(D3DFMT.A8, 1),
    [C.SVGA3D_R_S10E5]: f(D3DFMT.R16F, 2, target),
    [C.SVGA3D_R_S23E8]: f(D3DFMT.R32F, 4, target),
    [C.SVGA3D_RG_S10E5]: f(D3DFMT.G16R16F, 4, target),
    [C.SVGA3D_RG_S23E8]: f(D3DFMT.G32R32F, 8, target),
    [C.SVGA3D_BUFFER]: f(0, 1),
    [C.SVGA3D_Z_D24X8]: f(D3DFMT.D24X8, 4, depth),
    [C.SVGA3D_V16U16]: f(D3DFMT.V16U16, 4),
    [C.SVGA3D_G16R16]: f(D3DFMT.G16R16, 4, target),
    [C.SVGA3D_A16B16G16R16]: f(D3DFMT.A16B16G16R16, 8, target),
    [C.SVGA3D_UYVY]: f(D3DFMT.UYVY, 2),
    [C.SVGA3D_YUY2]: f(D3DFMT.YUY2, 2),
    [C.SVGA3D_P8]: f(D3DFMT.P8, 1),
    [C.SVGA3D_Z_DF16]: f(D3DFMT.DF16, 2, depth),
    [C.SVGA3D_Z_DF24]: f(D3DFMT.DF24, 4, depth),
    [C.SVGA3D_Z_D24S8_INT]: f(D3DFMT.INTZ, 4, depth),
    [C.SVGA3D_ATI1]: f(D3DFMT.ATI1, 8, block),
    [C.SVGA3D_ATI2]: f(D3DFMT.ATI2, 16, block),
    // DX names some guests use for the same storage
    [C.SVGA3D_B8G8R8A8_UNORM]: f(D3DFMT.A8R8G8B8, 4, target),
    [C.SVGA3D_B8G8R8X8_UNORM]: f(D3DFMT.X8R8G8B8, 4, target),
    [C.SVGA3D_R8G8B8A8_UNORM]: f(D3DFMT.A8B8G8R8, 4, target),
    [C.SVGA3D_B5G6R5_UNORM]: f(D3DFMT.R5G6B5, 2, target),
    [C.SVGA3D_B5G5R5A1_UNORM]: f(D3DFMT.A1R5G5B5, 2, target),
    [C.SVGA3D_R10G10B10A2_UNORM]: f(D3DFMT.A2B10G10R10, 4, target),
    [C.SVGA3D_R16G16B16A16_FLOAT]: f(D3DFMT.A16B16G16R16F, 8, target),
    [C.SVGA3D_R32G32B32A32_FLOAT]: f(D3DFMT.A32B32G32R32F, 16, target),
    [C.SVGA3D_R16G16_FLOAT]: f(D3DFMT.G16R16F, 4, target),
    [C.SVGA3D_R32G32_FLOAT]: f(D3DFMT.G32R32F, 8, target),
    [C.SVGA3D_R16_FLOAT]: f(D3DFMT.R16F, 2, target),
    [C.SVGA3D_R32_FLOAT]: f(D3DFMT.R32F, 4, target),
    [C.SVGA3D_R16G16_UNORM]: f(D3DFMT.G16R16, 4, target),
    [C.SVGA3D_R16G16B16A16_UNORM]: f(D3DFMT.A16B16G16R16, 8, target),
    [C.SVGA3D_A8_UNORM]: f(D3DFMT.A8, 1),
    [C.SVGA3D_BC1_UNORM]: f(D3DFMT.DXT1, 8, block),
    [C.SVGA3D_BC2_UNORM]: f(D3DFMT.DXT3, 16, block),
    [C.SVGA3D_BC3_UNORM]: f(D3DFMT.DXT5, 16, block),
    [C.SVGA3D_BC4_UNORM]: f(D3DFMT.ATI1, 8, block),
    [C.SVGA3D_BC5_UNORM]: f(D3DFMT.ATI2, 16, block),
    [C.SVGA3D_D16_UNORM]: f(D3DFMT.D16, 2, depth),
    [C.SVGA3D_D24_UNORM_S8_UINT]: f(D3DFMT.D24S8, 4, depth),
    [C.SVGA3D_D32_FLOAT]: f(D3DFMT.D32F_LOCKABLE, 4, depth),
};

// SVGA3dSurfaceFormatCaps, what D3D9 calls format operations
const TEXTURE = C.SVGA3DFORMAT_OP_TEXTURE | C.SVGA3DFORMAT_OP_VOLUMETEXTURE | C.SVGA3DFORMAT_OP_CUBETEXTURE;
const RENDER = C.SVGA3DFORMAT_OP_OFFSCREEN_RENDERTARGET | C.SVGA3DFORMAT_OP_SAME_FORMAT_RENDERTARGET;
const ZSTENCIL = C.SVGA3DFORMAT_OP_ZSTENCIL | C.SVGA3DFORMAT_OP_ZSTENCIL_WITH_ARBITRARY_COLOR_DEPTH;
// The D3D9 runtime disables the whole driver (no HAL, D3DERR_NOTAVAILABLE)
// if the format list breaks one of its rules (d3d9 ddcreate.cpp): 3D
// acceleration only on display modes without alpha, not both R5G6B5 and
// X1R5G5B5 as display modes, and the ARGB group only on the 8-bit and
// 16-bit RGB formats, A2R10G10B10, A16B16G16R16 and their float versions.
const DISPLAY = C.SVGA3DFORMAT_OP_DISPLAYMODE | C.SVGA3DFORMAT_OP_3DACCELERATION;
const COLOR_TARGET = TEXTURE | RENDER | C.SVGA3DFORMAT_OP_OFFSCREENPLAIN | C.SVGA3DFORMAT_OP_CONVERT_TO_ARGB |
    C.SVGA3DFORMAT_OP_AUTOGENMIPMAP;
const ARGB = COLOR_TARGET | C.SVGA3DFORMAT_OP_MEMBEROFGROUP_ARGB;
const PLAIN = TEXTURE | C.SVGA3DFORMAT_OP_OFFSCREENPLAIN;
const BUMP = PLAIN | C.SVGA3DFORMAT_OP_BUMPMAP;

/**
 * The devcaps the device reports at level vgpu9: shader model 3.0, the
 * formats the executor implements. 3DMark06 checks VS/PS 3.0, four render
 * targets, fp16 targets that blend and filter, and depth textures.
 * @type {!Array<!Array<number>>} [SVGA3D_DEVCAP_*, value]
 */
export const VGPU9_DEVCAPS = [
    [C.SVGA3D_DEVCAP_3D, 1],
    [C.SVGA3D_DEVCAP_MAX_LIGHTS, 8],
    [C.SVGA3D_DEVCAP_MAX_TEXTURES, 8],
    [C.SVGA3D_DEVCAP_MAX_CLIP_PLANES, 6],
    [C.SVGA3D_DEVCAP_VERTEX_SHADER_VERSION, C.SVGA3DVSVERSION_30],
    [C.SVGA3D_DEVCAP_VERTEX_SHADER, 1],
    [C.SVGA3D_DEVCAP_FRAGMENT_SHADER_VERSION, C.SVGA3DPSVERSION_30],
    [C.SVGA3D_DEVCAP_FRAGMENT_SHADER, 1],
    [C.SVGA3D_DEVCAP_MAX_RENDER_TARGETS, 4],
    [C.SVGA3D_DEVCAP_S23E8_TEXTURES, 1],
    [C.SVGA3D_DEVCAP_S10E5_TEXTURES, 1],
    [C.SVGA3D_DEVCAP_MAX_FIXED_VERTEXBLEND, 4],
    [C.SVGA3D_DEVCAP_D16_BUFFER_FORMAT, 1],
    [C.SVGA3D_DEVCAP_D24S8_BUFFER_FORMAT, 1],
    [C.SVGA3D_DEVCAP_D24X8_BUFFER_FORMAT, 1],
    [C.SVGA3D_DEVCAP_QUERY_TYPES, 1 << C.SVGA3D_QUERYTYPE_OCCLUSION],
    [C.SVGA3D_DEVCAP_TEXTURE_GRADIENT_SAMPLING, 1],
    [C.SVGA3D_DEVCAP_MAX_POINT_SIZE, f32_bits(64)],
    [C.SVGA3D_DEVCAP_MAX_SHADER_TEXTURES, 16],
    [C.SVGA3D_DEVCAP_MAX_TEXTURE_WIDTH, 8192],
    [C.SVGA3D_DEVCAP_MAX_TEXTURE_HEIGHT, 8192],
    [C.SVGA3D_DEVCAP_MAX_VOLUME_EXTENT, 2048],
    [C.SVGA3D_DEVCAP_MAX_TEXTURE_REPEAT, 8192],
    [C.SVGA3D_DEVCAP_MAX_TEXTURE_ASPECT_RATIO, 8192],
    [C.SVGA3D_DEVCAP_MAX_TEXTURE_ANISOTROPY, 16],
    [C.SVGA3D_DEVCAP_MAX_PRIMITIVE_COUNT, 0xFFFFF],
    [C.SVGA3D_DEVCAP_MAX_VERTEX_INDEX, 0xFFFFFF],
    [C.SVGA3D_DEVCAP_MAX_VERTEX_SHADER_INSTRUCTIONS, 0xFFFF],
    [C.SVGA3D_DEVCAP_MAX_FRAGMENT_SHADER_INSTRUCTIONS, 0xFFFF],
    [C.SVGA3D_DEVCAP_MAX_VERTEX_SHADER_TEMPS, 32],
    [C.SVGA3D_DEVCAP_MAX_FRAGMENT_SHADER_TEMPS, 32],
    // every combiner of SVGA3dTextureCombiner
    [C.SVGA3D_DEVCAP_TEXTURE_OPS, (1 << C.SVGA3D_TC_MAX - 1) - 1],
    [C.SVGA3D_DEVCAP_SURFACEFMT_X8R8G8B8, ARGB | DISPLAY | C.SVGA3DFORMAT_OP_SRGBREAD | C.SVGA3DFORMAT_OP_SRGBWRITE | C.SVGA3DFORMAT_OP_VERTEXTEXTURE],
    [C.SVGA3D_DEVCAP_SURFACEFMT_A8R8G8B8, ARGB | C.SVGA3DFORMAT_OP_SAME_FORMAT_UP_TO_ALPHA_RENDERTARGET |
        C.SVGA3DFORMAT_OP_SRGBREAD | C.SVGA3DFORMAT_OP_SRGBWRITE | C.SVGA3DFORMAT_OP_VERTEXTEXTURE],
    [C.SVGA3D_DEVCAP_SURFACEFMT_A2R10G10B10, ARGB],
    [C.SVGA3D_DEVCAP_SURFACEFMT_X1R5G5B5, ARGB],
    [C.SVGA3D_DEVCAP_SURFACEFMT_A1R5G5B5, ARGB | C.SVGA3DFORMAT_OP_SAME_FORMAT_UP_TO_ALPHA_RENDERTARGET],
    [C.SVGA3D_DEVCAP_SURFACEFMT_A4R4G4B4, PLAIN | C.SVGA3DFORMAT_OP_CONVERT_TO_ARGB],
    [C.SVGA3D_DEVCAP_SURFACEFMT_R5G6B5, ARGB | DISPLAY],
    [C.SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE16, PLAIN],
    [C.SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE8_ALPHA8, PLAIN],
    [C.SVGA3D_DEVCAP_SURFACEFMT_ALPHA8, PLAIN],
    [C.SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE8, PLAIN],
    [C.SVGA3D_DEVCAP_SURFACEFMT_Z_D16, ZSTENCIL],
    [C.SVGA3D_DEVCAP_SURFACEFMT_Z_D24S8, ZSTENCIL | C.SVGA3DFORMAT_OP_TEXTURE],
    [C.SVGA3D_DEVCAP_SURFACEFMT_Z_D24X8, ZSTENCIL | C.SVGA3DFORMAT_OP_TEXTURE],
    [C.SVGA3D_DEVCAP_SURFACEFMT_DXT1, PLAIN],
    [C.SVGA3D_DEVCAP_SURFACEFMT_DXT2, PLAIN],
    [C.SVGA3D_DEVCAP_SURFACEFMT_DXT3, PLAIN],
    [C.SVGA3D_DEVCAP_SURFACEFMT_DXT4, PLAIN],
    [C.SVGA3D_DEVCAP_SURFACEFMT_DXT5, PLAIN],
    [C.SVGA3D_DEVCAP_SURFACEFMT_BUMPX8L8V8U8, BUMP],
    [C.SVGA3D_DEVCAP_SURFACEFMT_A2W10V10U10, BUMP],
    [C.SVGA3D_DEVCAP_SURFACEFMT_BUMPU8V8, BUMP],
    [C.SVGA3D_DEVCAP_SURFACEFMT_Q8W8V8U8, BUMP],
    [C.SVGA3D_DEVCAP_SURFACEFMT_CxV8U8, BUMP],
    [C.SVGA3D_DEVCAP_SURFACEFMT_R_S10E5, COLOR_TARGET | C.SVGA3DFORMAT_OP_VERTEXTEXTURE],
    [C.SVGA3D_DEVCAP_SURFACEFMT_R_S23E8, COLOR_TARGET | C.SVGA3DFORMAT_OP_VERTEXTEXTURE],
    [C.SVGA3D_DEVCAP_SURFACEFMT_RG_S10E5, COLOR_TARGET],
    [C.SVGA3D_DEVCAP_SURFACEFMT_RG_S23E8, COLOR_TARGET],
    [C.SVGA3D_DEVCAP_SURFACEFMT_ARGB_S10E5, ARGB | C.SVGA3DFORMAT_OP_VERTEXTEXTURE],
    [C.SVGA3D_DEVCAP_SURFACEFMT_ARGB_S23E8, ARGB | C.SVGA3DFORMAT_OP_VERTEXTEXTURE],
    [C.SVGA3D_DEVCAP_MAX_VERTEX_SHADER_TEXTURES, 4],
    [C.SVGA3D_DEVCAP_MAX_SIMULTANEOUS_RENDER_TARGETS, 4],
    [C.SVGA3D_DEVCAP_SURFACEFMT_V16U16, BUMP],
    [C.SVGA3D_DEVCAP_SURFACEFMT_G16R16, COLOR_TARGET],
    [C.SVGA3D_DEVCAP_SURFACEFMT_A16B16G16R16, ARGB],
    [C.SVGA3D_DEVCAP_SURFACEFMT_UYVY, C.SVGA3DFORMAT_OP_OFFSCREENPLAIN | C.SVGA3DFORMAT_OP_TEXTURE],
    [C.SVGA3D_DEVCAP_SURFACEFMT_YUY2, C.SVGA3DFORMAT_OP_OFFSCREENPLAIN | C.SVGA3DFORMAT_OP_TEXTURE],
    [C.SVGA3D_DEVCAP_AUTOGENMIPMAPS, 1],
    [C.SVGA3D_DEVCAP_MAX_CONTEXT_IDS, 256],
    [C.SVGA3D_DEVCAP_MAX_SURFACE_IDS, 32768],
    [C.SVGA3D_DEVCAP_SURFACEFMT_Z_DF16, ZSTENCIL | C.SVGA3DFORMAT_OP_TEXTURE],
    [C.SVGA3D_DEVCAP_SURFACEFMT_Z_DF24, ZSTENCIL | C.SVGA3DFORMAT_OP_TEXTURE],
    [C.SVGA3D_DEVCAP_SURFACEFMT_Z_D24S8_INT, ZSTENCIL | C.SVGA3DFORMAT_OP_TEXTURE],
    [C.SVGA3D_DEVCAP_SURFACEFMT_ATI1, PLAIN],
    [C.SVGA3D_DEVCAP_SURFACEFMT_ATI2, PLAIN],
    [C.SVGA3D_DEVCAP_LINE_AA, 1],
    [C.SVGA3D_DEVCAP_LINE_STIPPLE, 0],
    [C.SVGA3D_DEVCAP_MAX_LINE_WIDTH, f32_bits(1)],
    [C.SVGA3D_DEVCAP_MAX_AA_LINE_WIDTH, f32_bits(1)],
];

/**
 * The devcaps at level dx10: those of vgpu9, DX contexts, and per format what
 * GX does with it (svga_dx_formats.js)
 * @type {!Array<!Array<number>>}
 */
export const DX10_DEVCAPS = [
    ...VGPU9_DEVCAPS,
    [C.SVGA3D_DEVCAP_DXCONTEXT, 1],
    [C.SVGA3D_DEVCAP_DX_MAX_VERTEXBUFFERS, 16],
    [C.SVGA3D_DEVCAP_DX_MAX_CONSTANT_BUFFERS, 14],
    // the first vertex provokes (WebGPU's), not chosen per draw
    [C.SVGA3D_DEVCAP_DX_PROVOKING_VERTEX, 0],
    [C.SVGA3D_DEVCAP_MULTISAMPLE_2X, 0],
    [C.SVGA3D_DEVCAP_MULTISAMPLE_4X, 1],
    [C.SVGA3D_DEVCAP_MS_FULL_QUALITY, 0],
    [C.SVGA3D_DEVCAP_SM41, 0],
    [C.SVGA3D_DEVCAP_SM5, 0],
    ...dx_format_caps("dx10"),
];

/**
 * The devcaps at level dx10.1: dx10's and shader model 4.1, with what
 * VMware's driver wants before it offers feature level 10_1 (its table,
 * vm3dum64_10.dll at 0x180060a20): 4x multisampling of every target format
 * (GX supersamples), and from Direct3D 11.1 on NV12 and YUY2 surfaces,
 * R10G10B10_XR_BIAS_A2_UNORM ones and B8G8R8X8_UNORM vertices. GX keeps
 * the NV12 and YUY2 surfaces in guest memory only: they are made and copied,
 * never sampled or drawn into.
 * @type {!Array<!Array<number>>}
 */
export const DX10_1_DEVCAPS = with_devcaps(DX10_DEVCAPS, [
    [C.SVGA3D_DEVCAP_SM41, 1],
    ...dx_format_caps("dx10.1"),
    [C.SVGA3D_DEVCAP_DXFMT_YUY2, C.SVGA3D_DXFMT_SUPPORTED],
    [C.SVGA3D_DEVCAP_DXFMT_NV12, C.SVGA3D_DXFMT_SUPPORTED],
]);

/**
 * The devcaps at level dx11: dx10.1's and shader model 5 (compute, UAVs,
 * tessellation: GX emulates the stages WebGPU lacks), 8x multisampling
 * (supersampled 4 x 2), 16384-texel textures, and what Linux's vmwgfx and
 * Mesa want for GL 4.3: the GL43 devcap and a forced sample count of at
 * least 4 (draws without targets)
 * @type {!Array<!Array<number>>}
 */
export const DX11_DEVCAPS = with_devcaps(DX10_1_DEVCAPS, [
    [C.SVGA3D_DEVCAP_SM5, 1],
    [C.SVGA3D_DEVCAP_MULTISAMPLE_8X, 1],
    [C.SVGA3D_DEVCAP_MAX_FORCED_SAMPLE_COUNT, 8],
    [C.SVGA3D_DEVCAP_GL43, 1],
    [C.SVGA3D_DEVCAP_MAX_TEXTURE_WIDTH, 16384],
    [C.SVGA3D_DEVCAP_MAX_TEXTURE_HEIGHT, 16384],
    [C.SVGA3D_DEVCAP_MAX_TEXTURE_REPEAT, 16384],
]);

/**
 * The devcaps at level dx11-full: dx11's, and the last vertex provoking where
 * the rasterizer state asks (GX reorders: GL's flat shading, which Mesa's
 * svga otherwise converts in the guest)
 * @type {!Array<!Array<number>>}
 */
export const DX11_FULL_DEVCAPS = with_devcaps(DX11_DEVCAPS, [
    [C.SVGA3D_DEVCAP_DX_PROVOKING_VERTEX, 1],
]);

/** A level's devcaps from the one below's, some of them changed */
function with_devcaps(base, changes)
{
    const caps = new Map(base);
    for(const [index, value] of changes) caps.set(index, value);
    return Array.from(caps);
}

/**
 * SVGA3D_DEVCAP_DXFMT_* from svga_dx_formats.js, at a level: dx10 leaves out
 * what came later (AFTER_DX10) and multisamples the "m" formats only
 * @param {string} level
 */
function dx_format_caps(level)
{
    const dx10 = level === "dx10";
    const caps = [];
    for(const name of Object.keys(DX_FORMATS))
    {
        const index = C["SVGA3D_DEVCAP_DXFMT_" + name.slice("SVGA3D_".length)];
        if(index === undefined || dx10 && AFTER_DX10.formats.has(name)) continue;
        const [texture, can] = DX_FORMATS[name];
        const vertex = dx10 && AFTER_DX10.vertex.has(name) ? "" : DX_FORMATS[name][2];
        let value = 0;
        if(texture || vertex) value |= C.SVGA3D_DXFMT_SUPPORTED;
        if(can.includes("s") || can.includes("u")) value |= C.SVGA3D_DXFMT_SHADER_SAMPLE;
        if(can.includes("r")) value |= C.SVGA3D_DXFMT_COLOR_RENDERTARGET;
        if(can.includes("d")) value |= C.SVGA3D_DXFMT_DEPTH_RENDERTARGET;
        if(can.includes("b")) value |= C.SVGA3D_DXFMT_BLENDABLE;
        if(texture) value |= C.SVGA3D_DXFMT_MIPS | C.SVGA3D_DXFMT_ARRAY;
        if(texture && !can.includes("d")) value |= C.SVGA3D_DXFMT_VOLUME;
        if(vertex) value |= C.SVGA3D_DXFMT_DX_VERTEX_BUFFER;
        if(dx10 ? can.includes("m") : texture && (can.includes("r") || can.includes("d"))) value |= C.SVGA3D_DXFMT_MULTISAMPLE;
        caps.push([index, value]);
    }
    // a buffer is supported as one
    caps.push([C.SVGA3D_DEVCAP_DXFMT_BUFFER, C.SVGA3D_DXFMT_SUPPORTED]);
    return caps;
}

function f32_bits(value)
{
    return new Uint32Array(new Float32Array([value]).buffer)[0];
}

/** SVGA3dPrimitiveType -> D3DPRIMITIVETYPE, and the vertices of n primitives */
export const PRIMITIVES = {
    [C.SVGA3D_PRIMITIVE_TRIANGLELIST]: 4,
    [C.SVGA3D_PRIMITIVE_POINTLIST]: 1,
    [C.SVGA3D_PRIMITIVE_LINELIST]: 2,
    [C.SVGA3D_PRIMITIVE_LINESTRIP]: 3,
    [C.SVGA3D_PRIMITIVE_TRIANGLESTRIP]: 5,
    [C.SVGA3D_PRIMITIVE_TRIANGLEFAN]: 6,
};

/** @return {number} the vertices (or indices) n primitives of a D3DPRIMITIVETYPE take */
export function primitive_vertices(d3d_type, count)
{
    switch(d3d_type)
    {
        case 1: return count;
        case 2: return count * 2;
        case 3: return count + 1;
        case 4: return count * 3;
        default: return count + 2;
    }
}

/** SVGA3dTransformType -> D3DTRANSFORMSTATETYPE */
export function d3d_transform(type)
{
    if(type === C.SVGA3D_TRANSFORM_WORLD) return 256;
    if(type === C.SVGA3D_TRANSFORM_VIEW) return 2;
    if(type === C.SVGA3D_TRANSFORM_PROJECTION) return 3;
    if(type >= C.SVGA3D_TRANSFORM_TEXTURE0 && type <= C.SVGA3D_TRANSFORM_TEXTURE7) return 16 + type - C.SVGA3D_TRANSFORM_TEXTURE0;
    if(type >= C.SVGA3D_TRANSFORM_WORLD1 && type <= C.SVGA3D_TRANSFORM_WORLD3) return 257 + type - C.SVGA3D_TRANSFORM_WORLD1;
    return -1;
}

/** SVGA3dLightType -> D3DLIGHTTYPE (both spot models are D3D's one) */
export function d3d_light_type(type)
{
    return type === C.SVGA3D_LIGHTTYPE_POINT ? 1 : type === C.SVGA3D_LIGHTTYPE_DIRECTIONAL ? 3 : 2;
}

// D3DRENDERSTATETYPE
export const D3DRS = {
    ZENABLE: 7, FILLMODE: 8, SHADEMODE: 9, ZWRITEENABLE: 14, ALPHATESTENABLE: 15, LASTPIXEL: 16,
    SRCBLEND: 19, DESTBLEND: 20, CULLMODE: 22, ZFUNC: 23, ALPHAREF: 24, ALPHAFUNC: 25,
    DITHERENABLE: 26, ALPHABLENDENABLE: 27, FOGENABLE: 28, SPECULARENABLE: 29, FOGCOLOR: 34,
    FOGTABLEMODE: 35, FOGSTART: 36, FOGEND: 37, FOGDENSITY: 38, RANGEFOGENABLE: 48,
    STENCILENABLE: 52, STENCILFAIL: 53, STENCILZFAIL: 54, STENCILPASS: 55, STENCILFUNC: 56,
    STENCILREF: 57, STENCILMASK: 58, STENCILWRITEMASK: 59, TEXTUREFACTOR: 60, WRAP0: 128,
    CLIPPING: 136, LIGHTING: 137, AMBIENT: 139, FOGVERTEXMODE: 140, COLORVERTEX: 141,
    LOCALVIEWER: 142, NORMALIZENORMALS: 143, DIFFUSEMATERIALSOURCE: 145,
    SPECULARMATERIALSOURCE: 146, AMBIENTMATERIALSOURCE: 147, EMISSIVEMATERIALSOURCE: 148,
    VERTEXBLEND: 151, CLIPPLANEENABLE: 152, POINTSIZE: 154, POINTSIZE_MIN: 155,
    POINTSPRITEENABLE: 156, POINTSCALEENABLE: 157, POINTSCALE_A: 158, POINTSCALE_B: 159,
    POINTSCALE_C: 160, MULTISAMPLEANTIALIAS: 161, MULTISAMPLEMASK: 162, POINTSIZE_MAX: 166,
    INDEXEDVERTEXBLENDENABLE: 167, COLORWRITEENABLE: 168, TWEENFACTOR: 170, BLENDOP: 171,
    SCISSORTESTENABLE: 174, SLOPESCALEDEPTHBIAS: 175, ANTIALIASEDLINEENABLE: 176,
    TWOSIDEDSTENCILMODE: 185, CCW_STENCILFAIL: 186, CCW_STENCILZFAIL: 187, CCW_STENCILPASS: 188,
    CCW_STENCILFUNC: 189, COLORWRITEENABLE1: 190, COLORWRITEENABLE2: 191, COLORWRITEENABLE3: 192,
    BLENDFACTOR: 193, SRGBWRITEENABLE: 194, DEPTHBIAS: 195, WRAP8: 198,
    SEPARATEALPHABLENDENABLE: 206, SRCBLENDALPHA: 207, DESTBLENDALPHA: 208, BLENDOPALPHA: 209,
};

/** Render states whose values D3D9 spells the same way: SVGA3D_RS_* -> D3DRS_* */
export const SAME_RENDER_STATES = {
    [C.SVGA3D_RS_ZENABLE]: D3DRS.ZENABLE,
    [C.SVGA3D_RS_ZWRITEENABLE]: D3DRS.ZWRITEENABLE,
    [C.SVGA3D_RS_ALPHATESTENABLE]: D3DRS.ALPHATESTENABLE,
    [C.SVGA3D_RS_DITHERENABLE]: D3DRS.DITHERENABLE,
    [C.SVGA3D_RS_BLENDENABLE]: D3DRS.ALPHABLENDENABLE,
    [C.SVGA3D_RS_FOGENABLE]: D3DRS.FOGENABLE,
    [C.SVGA3D_RS_SPECULARENABLE]: D3DRS.SPECULARENABLE,
    [C.SVGA3D_RS_STENCILENABLE]: D3DRS.STENCILENABLE,
    [C.SVGA3D_RS_LIGHTINGENABLE]: D3DRS.LIGHTING,
    [C.SVGA3D_RS_NORMALIZENORMALS]: D3DRS.NORMALIZENORMALS,
    [C.SVGA3D_RS_POINTSPRITEENABLE]: D3DRS.POINTSPRITEENABLE,
    [C.SVGA3D_RS_POINTSCALEENABLE]: D3DRS.POINTSCALEENABLE,
    [C.SVGA3D_RS_STENCILREF]: D3DRS.STENCILREF,
    [C.SVGA3D_RS_STENCILMASK]: D3DRS.STENCILMASK,
    [C.SVGA3D_RS_STENCILWRITEMASK]: D3DRS.STENCILWRITEMASK,
    [C.SVGA3D_RS_FOGSTART]: D3DRS.FOGSTART,
    [C.SVGA3D_RS_FOGEND]: D3DRS.FOGEND,
    [C.SVGA3D_RS_FOGDENSITY]: D3DRS.FOGDENSITY,
    [C.SVGA3D_RS_POINTSIZE]: D3DRS.POINTSIZE,
    [C.SVGA3D_RS_POINTSIZEMIN]: D3DRS.POINTSIZE_MIN,
    [C.SVGA3D_RS_POINTSIZEMAX]: D3DRS.POINTSIZE_MAX,
    [C.SVGA3D_RS_POINTSCALE_A]: D3DRS.POINTSCALE_A,
    [C.SVGA3D_RS_POINTSCALE_B]: D3DRS.POINTSCALE_B,
    [C.SVGA3D_RS_POINTSCALE_C]: D3DRS.POINTSCALE_C,
    [C.SVGA3D_RS_FOGCOLOR]: D3DRS.FOGCOLOR,
    [C.SVGA3D_RS_AMBIENT]: D3DRS.AMBIENT,
    [C.SVGA3D_RS_CLIPPLANEENABLE]: D3DRS.CLIPPLANEENABLE,
    [C.SVGA3D_RS_SHADEMODE]: D3DRS.SHADEMODE,
    [C.SVGA3D_RS_BLENDEQUATION]: D3DRS.BLENDOP,
    [C.SVGA3D_RS_ZFUNC]: D3DRS.ZFUNC,
    [C.SVGA3D_RS_ALPHAFUNC]: D3DRS.ALPHAFUNC,
    [C.SVGA3D_RS_STENCILFUNC]: D3DRS.STENCILFUNC,
    [C.SVGA3D_RS_STENCILFAIL]: D3DRS.STENCILFAIL,
    [C.SVGA3D_RS_STENCILZFAIL]: D3DRS.STENCILZFAIL,
    [C.SVGA3D_RS_STENCILPASS]: D3DRS.STENCILPASS,
    [C.SVGA3D_RS_COLORWRITEENABLE]: D3DRS.COLORWRITEENABLE,
    [C.SVGA3D_RS_VERTEXMATERIALENABLE]: D3DRS.COLORVERTEX,
    [C.SVGA3D_RS_DIFFUSEMATERIALSOURCE]: D3DRS.DIFFUSEMATERIALSOURCE,
    [C.SVGA3D_RS_SPECULARMATERIALSOURCE]: D3DRS.SPECULARMATERIALSOURCE,
    [C.SVGA3D_RS_AMBIENTMATERIALSOURCE]: D3DRS.AMBIENTMATERIALSOURCE,
    [C.SVGA3D_RS_EMISSIVEMATERIALSOURCE]: D3DRS.EMISSIVEMATERIALSOURCE,
    [C.SVGA3D_RS_TEXTUREFACTOR]: D3DRS.TEXTUREFACTOR,
    [C.SVGA3D_RS_LOCALVIEWER]: D3DRS.LOCALVIEWER,
    [C.SVGA3D_RS_SCISSORTESTENABLE]: D3DRS.SCISSORTESTENABLE,
    [C.SVGA3D_RS_BLENDCOLOR]: D3DRS.BLENDFACTOR,
    [C.SVGA3D_RS_STENCILENABLE2SIDED]: D3DRS.TWOSIDEDSTENCILMODE,
    [C.SVGA3D_RS_CCWSTENCILFUNC]: D3DRS.CCW_STENCILFUNC,
    [C.SVGA3D_RS_CCWSTENCILFAIL]: D3DRS.CCW_STENCILFAIL,
    [C.SVGA3D_RS_CCWSTENCILZFAIL]: D3DRS.CCW_STENCILZFAIL,
    [C.SVGA3D_RS_CCWSTENCILPASS]: D3DRS.CCW_STENCILPASS,
    [C.SVGA3D_RS_VERTEXBLEND]: D3DRS.VERTEXBLEND,
    [C.SVGA3D_RS_SLOPESCALEDEPTHBIAS]: D3DRS.SLOPESCALEDEPTHBIAS,
    [C.SVGA3D_RS_DEPTHBIAS]: D3DRS.DEPTHBIAS,
    [C.SVGA3D_RS_LASTPIXEL]: D3DRS.LASTPIXEL,
    [C.SVGA3D_RS_CLIPPING]: D3DRS.CLIPPING,
    [C.SVGA3D_RS_MULTISAMPLEANTIALIAS]: D3DRS.MULTISAMPLEANTIALIAS,
    [C.SVGA3D_RS_MULTISAMPLEMASK]: D3DRS.MULTISAMPLEMASK,
    [C.SVGA3D_RS_INDEXEDVERTEXBLENDENABLE]: D3DRS.INDEXEDVERTEXBLENDENABLE,
    [C.SVGA3D_RS_TWEENFACTOR]: D3DRS.TWEENFACTOR,
    [C.SVGA3D_RS_ANTIALIASEDLINEENABLE]: D3DRS.ANTIALIASEDLINEENABLE,
    [C.SVGA3D_RS_COLORWRITEENABLE1]: D3DRS.COLORWRITEENABLE1,
    [C.SVGA3D_RS_COLORWRITEENABLE2]: D3DRS.COLORWRITEENABLE2,
    [C.SVGA3D_RS_COLORWRITEENABLE3]: D3DRS.COLORWRITEENABLE3,
    [C.SVGA3D_RS_SEPARATEALPHABLENDENABLE]: D3DRS.SEPARATEALPHABLENDENABLE,
    [C.SVGA3D_RS_BLENDEQUATIONALPHA]: D3DRS.BLENDOPALPHA,
};

/** SVGA3dBlendOp -> D3DBLEND: the same up to SRCALPHASAT; D3D9 has BOTHSRCALPHA in between */
export function d3d_blend(value)
{
    if(value === C.SVGA3D_BLENDOP_BLENDFACTOR) return 14;
    if(value === C.SVGA3D_BLENDOP_INVBLENDFACTOR) return 15;
    return value;
}

// D3DTEXTURESTAGESTATETYPE and D3DSAMPLERSTATETYPE
export const D3DTSS = {
    COLOROP: 1, COLORARG1: 2, COLORARG2: 3, ALPHAOP: 4, ALPHAARG1: 5, ALPHAARG2: 6,
    BUMPENVMAT00: 7, BUMPENVMAT01: 8, BUMPENVMAT10: 9, BUMPENVMAT11: 10, TEXCOORDINDEX: 11,
    BUMPENVLSCALE: 22, BUMPENVLOFFSET: 23, TEXTURETRANSFORMFLAGS: 24, COLORARG0: 26,
    ALPHAARG0: 27, CONSTANT: 32,
};
export const D3DSAMP = {
    ADDRESSU: 1, ADDRESSV: 2, ADDRESSW: 3, BORDERCOLOR: 4, MAGFILTER: 5, MINFILTER: 6,
    MIPFILTER: 7, MIPMAPLODBIAS: 8, MAXMIPLEVEL: 9, MAXANISOTROPY: 10, SRGBTEXTURE: 11,
};

/** SVGA3dTextureCombiner -> D3DTEXTUREOP */
export const TEXTURE_OPS = {
    [C.SVGA3D_TC_DISABLE]: 1, [C.SVGA3D_TC_SELECTARG1]: 2, [C.SVGA3D_TC_SELECTARG2]: 3,
    [C.SVGA3D_TC_MODULATE]: 4, [C.SVGA3D_TC_ADD]: 7, [C.SVGA3D_TC_ADDSIGNED]: 8,
    [C.SVGA3D_TC_SUBTRACT]: 10, [C.SVGA3D_TC_BLENDTEXTUREALPHA]: 13,
    [C.SVGA3D_TC_BLENDDIFFUSEALPHA]: 12, [C.SVGA3D_TC_BLENDCURRENTALPHA]: 16,
    [C.SVGA3D_TC_BLENDFACTORALPHA]: 14, [C.SVGA3D_TC_MODULATE2X]: 5, [C.SVGA3D_TC_MODULATE4X]: 6,
    [C.SVGA3D_TC_DSDT]: 22, [C.SVGA3D_TC_DOTPRODUCT3]: 24, [C.SVGA3D_TC_BLENDTEXTUREALPHAPM]: 15,
    [C.SVGA3D_TC_ADDSIGNED2X]: 9, [C.SVGA3D_TC_ADDSMOOTH]: 11, [C.SVGA3D_TC_PREMODULATE]: 17,
    [C.SVGA3D_TC_MODULATEALPHA_ADDCOLOR]: 18, [C.SVGA3D_TC_MODULATECOLOR_ADDALPHA]: 19,
    [C.SVGA3D_TC_MODULATEINVALPHA_ADDCOLOR]: 20, [C.SVGA3D_TC_MODULATEINVCOLOR_ADDALPHA]: 21,
    [C.SVGA3D_TC_BUMPENVMAPLUMINANCE]: 23, [C.SVGA3D_TC_MULTIPLYADD]: 25, [C.SVGA3D_TC_LERP]: 26,
};

/**
 * SVGA3dTextureArgData plus modifiers -> D3DTA_*: the sources are numbered
 * differently, and SVGA3D's ALPHA and ONE_MINUS bits are D3D's
 * ALPHAREPLICATE and COMPLEMENT the other way round
 */
export function d3d_texture_argument(value)
{
    const source = { [C.SVGA3D_TA_TFACTOR]: 3, [C.SVGA3D_TA_PREVIOUS]: 1, [C.SVGA3D_TA_DIFFUSE]: 0,
        [C.SVGA3D_TA_TEXTURE]: 2, [C.SVGA3D_TA_SPECULAR]: 4, [C.SVGA3D_TA_CONSTANT]: 6 }[value & 0xF];
    return (source === undefined ? 1 : source) |
        (value & C.SVGA3D_TM_ALPHA ? 0x20 : 0) | (value & C.SVGA3D_TM_ONE_MINUS ? 0x10 : 0);
}

/** SVGA3dTexTransformFlags -> D3DTEXTURETRANSFORMFLAGS: a coordinate count */
export function d3d_texture_transform_flags(value)
{
    const count = (value & 1) + (value >> 1 & 1) + (value >> 2 & 1) + (value >> 3 & 1);
    return count | (value & C.SVGA3D_TEX_PROJECTED ? 256 : 0);
}

/** SVGA3D_TEX_ADDRESS_EDGE is D3D's clamp; the rest are numbered alike */
export function d3d_address(value)
{
    return value === C.SVGA3D_TEX_ADDRESS_EDGE ? 3 : value;
}

/** SVGA3dTextureCoordGen -> the D3DTSS_TCI_* bits of TEXCOORDINDEX */
export function d3d_texcoord_generation(value)
{
    return {
        [C.SVGA3D_TEXCOORD_GEN_EYE_POSITION]: 0x20000,
        [C.SVGA3D_TEXCOORD_GEN_EYE_NORMAL]: 0x10000,
        [C.SVGA3D_TEXCOORD_GEN_REFLECTIONVECTOR]: 0x30000,
        [C.SVGA3D_TEXCOORD_GEN_SPHERE]: 0x40000,
    }[value] || 0;
}
