//! The CPU features of docs/simd-xsave-plan.md (SSSE3 to x86-64-v3 and the
//! XSAVE family) that this machine has, fixed when it is created (settings
//! `cpu_features`, src/cpu.js). CPUID reports them, and the decoders and
//! executors test them: an opcode row whose feature is absent does not exist
//! (decode_rules::mandatory_variant), so its encoding is #UD, or for TZCNT and
//! LZCNT the older BSF and BSR.

// BEGIN GENERATED by gen/cpu_features.js (edit the table there)
pub const SSSE3: u32 = 1 << 0;
pub const SSE4_1: u32 = 1 << 1;
pub const SSE4_2: u32 = 1 << 2;
pub const XSAVE: u32 = 1 << 3;
pub const AVX: u32 = 1 << 4;
pub const AVX2: u32 = 1 << 5;
pub const FMA: u32 = 1 << 6;
pub const F16C: u32 = 1 << 7;
pub const BMI1: u32 = 1 << 8;
pub const BMI2: u32 = 1 << 9;
pub const LZCNT: u32 = 1 << 10;
pub const MOVBE: u32 = 1 << 11;
pub const XSAVEOPT: u32 = 1 << 12;
pub const XSAVEC: u32 = 1 << 13;
pub const XGETBV1: u32 = 1 << 14;
pub const XSAVES: u32 = 1 << 15;
pub const COUNT: usize = 16;
pub const ALL: u32 = 0xFFFF;
/// The other features each one requires (the always-present ones left out)
pub const REQUIRES: [u32; COUNT] = [0, SSSE3, SSE4_1, 0, XSAVE | SSE4_2, AVX, AVX, AVX, 0, 0, 0, 0, XSAVE, XSAVE, XSAVE, XSAVEC];
/// Where CPUID reports each: (leaf, subleaf, register: 0 = EAX .. 3 = EDX, bit)
pub const CPUID: [(u32, u32, usize, u32); COUNT] = [(0x1, 0, 2, 9), (0x1, 0, 2, 19), (0x1, 0, 2, 20), (0x1, 0, 2, 26), (0x1, 0, 2, 28), (0x7, 0, 1, 5), (0x1, 0, 2, 12), (0x1, 0, 2, 29), (0x7, 0, 1, 3), (0x7, 0, 1, 8), (0x80000001, 0, 2, 5), (0x1, 0, 2, 22), (0xD, 1, 0, 0), (0xD, 1, 0, 1), (0xD, 1, 0, 2), (0xD, 1, 0, 3)];
/// The lowest maximum basic leaf (cpuid_level) that lets CPUID report each
pub const MIN_CPUID_LEVEL: [u32; COUNT] = [0x1, 0x1, 0x1, 0xD, 0x1, 0x7, 0x1, 0x1, 0x7, 0x7, 0x1, 0x1, 0xD, 0xD, 0xD, 0xD];
/// Features the legacy (x86) profile may not have
pub const X86_64_ONLY: u32 = LZCNT;
// END GENERATED

/// The features of this machine (bits above)
static mut FEATURES: u32 = 0;

/// Whether the machine has all of `features`
#[inline]
pub fn has(features: u32) -> bool { unsafe { FEATURES & features == features } }

/// The features of this machine
#[inline]
pub fn all() -> u32 { unsafe { FEATURES } }

/// Set by src/cpu.js before the CPU runs, after it checked requirements,
/// profile and cpuid_level (CPU.prototype.resolve_cpu_features)
#[no_mangle]
pub unsafe fn set_cpu_features(features: u32) {
    dbg_assert!(features & !ALL == 0);
    dbg_assert!(valid(features, crate::cpu::instructions_0f::long_mode_capable()));
    FEATURES = features;
}
#[no_mangle]
pub unsafe fn get_cpu_features() -> u32 { FEATURES }

/// A worker's cores have the machine's features (crate::parallel)
pub unsafe fn copy_from_machine() { FEATURES = *crate::parallel::machine(&raw mut FEATURES); }

/// Every feature's requirements are present, and the legacy profile has no
/// x86-64-only feature
pub fn valid(features: u32, x86_64: bool) -> bool {
    (0..COUNT).all(|i| features & 1 << i == 0 || features & REQUIRES[i] == REQUIRES[i])
        && (x86_64 || features & X86_64_ONLY == 0)
}

/// CPUID: set the bits of the machine's features in `registers` (EAX..EDX)
/// of leaf `leaf`, subleaf `subleaf` (ECX, which only leaves 7 and 0xD read)
pub fn cpuid(leaf: u32, subleaf: u32, registers: &mut [u32; 4]) {
    let indexed = matches!(leaf, 7 | 0xD);
    for (i, &(at_leaf, at_subleaf, register, bit)) in CPUID.iter().enumerate() {
        if all() & 1 << i != 0 && at_leaf == leaf && (!indexed || at_subleaf == subleaf) {
            registers[register] |= 1 << bit;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn requirements_and_cpuid_locations() {
        assert!(valid(0, false) && valid(ALL, true));
        assert!(!valid(SSE4_1, false), "SSE4.1 requires SSSE3");
        assert!(valid(SSSE3 | SSE4_1 | SSE4_2, false));
        assert!(!valid(AVX, true) && !valid(AVX | XSAVE, true) && valid(AVX | XSAVE | SSSE3 | SSE4_1 | SSE4_2, true));
        assert!(!valid(LZCNT, false) && valid(LZCNT, true), "LZCNT needs the extended leaves of the x86-64 profile");
        assert!(valid(BMI1 | BMI2 | MOVBE, false), "general-purpose extensions stand alone");
        assert_eq!(CPUID[SSSE3.trailing_zeros() as usize], (1, 0, 2, 9));
        assert_eq!(CPUID[AVX2.trailing_zeros() as usize], (7, 0, 1, 5));
        assert_eq!(CPUID[LZCNT.trailing_zeros() as usize], (0x8000_0001, 0, 2, 5));
        assert_eq!(MIN_CPUID_LEVEL[XSAVE.trailing_zeros() as usize], 0xD);
        assert_eq!(MIN_CPUID_LEVEL[BMI2.trailing_zeros() as usize], 7);
    }
}
