#![allow(non_upper_case_globals)]

use crate::cpu::cpu::reg128;
use crate::softfloat::F80;
use crate::state_flags::CachedStateFlags;

// BEGIN GENERATED by gen/state_layout.js (edit the layout there)
pub const reg8: *mut u8 = 64 as *mut u8;
pub const reg16: *mut u16 = 64 as *mut u16;
pub const reg32: *mut i32 = 64 as *mut i32;
pub const last_op_size: *mut i32 = 96 as *mut i32;
pub const flags_changed: *mut i32 = 100 as *mut i32;
pub const last_op1: *mut i32 = 104 as *mut i32;
pub const state_flags: *mut CachedStateFlags = 108 as *mut CachedStateFlags;
pub const last_result: *mut i32 = 112 as *mut i32;
pub const flags: *mut i32 = 120 as *mut i32;
pub const segment_access_bytes: *mut u8 = 512 as *mut u8; // TODO: reorder below segment_limits
pub const apic_enabled: *mut bool = 548 as *mut bool;
pub const acpi_enabled: *mut bool = 552 as *mut bool;
pub const instruction_pointer: *mut i32 = 556 as *mut i32;
pub const previous_ip: *mut i32 = 560 as *mut i32;
pub const idtr_size: *mut i32 = 564 as *mut i32;
pub const idtr_offset: *mut i32 = 568 as *mut i32;
pub const gdtr_size: *mut i32 = 572 as *mut i32;
pub const gdtr_offset: *mut i32 = 576 as *mut i32;
pub const cr: *mut i32 = 580 as *mut i32;
pub const cpl: *mut u8 = 612 as *mut u8;
pub const in_hlt: *mut bool = 616 as *mut bool;
pub const last_virt_eip: *mut i32 = 620 as *mut i32;
pub const eip_phys: *mut i32 = 624 as *mut i32;
pub const nmi_blocked: *mut bool = 628 as *mut bool;
pub const interrupt_shadow: *mut u8 = 632 as *mut u8;
pub const sysenter_cs: *mut i32 = 636 as *mut i32;
pub const sysenter_esp: *mut i32 = 640 as *mut i32;
pub const sysenter_eip: *mut i32 = 644 as *mut i32;
pub const prefixes: *mut u8 = 648 as *mut u8;
pub const instruction_counter: *mut u32 = 664 as *mut u32;
pub const sreg: *mut u16 = 668 as *mut u16;
pub const dreg: *mut i32 = 684 as *mut i32;
pub const svga_dirty_bitmap_min_offset: *mut u32 = 716 as *mut u32; // filled in by svga_fill_pixel_buffer, read by javacsript for optimised putImageData calls
pub const svga_dirty_bitmap_max_offset: *mut u32 = 720 as *mut u32;
pub const segment_is_null: *mut bool = 724 as *mut bool;
pub const segment_offsets: *mut i32 = 736 as *mut i32;
pub const segment_limits: *mut u32 = 768 as *mut u32;
pub const protected_mode: *mut bool = 800 as *mut bool;
pub const is_32: *mut bool = 804 as *mut bool;
pub const stack_size_32: *mut bool = 808 as *mut bool;
pub const memory_size: *mut u32 = 812 as *mut u32;
pub const fpu_stack_empty: *mut u8 = 816 as *mut u8;
pub const mxcsr: *mut i32 = 824 as *mut i32;
pub const reg_xmm: *mut reg128 = 832 as *mut reg128;
pub const current_tsc: *mut u64 = 960 as *mut u64;
pub const reg_pdpte: *mut u64 = 968 as *mut u64; // 4 64-bit entries
pub const fpu_stack_ptr: *mut u8 = 1032 as *mut u8;
pub const fpu_control_word: *mut u16 = 1036 as *mut u16;
pub const fpu_status_word: *mut u16 = 1040 as *mut u16;
pub const fpu_opcode: *mut i32 = 1044 as *mut i32;
pub const fpu_ip: *mut i32 = 1048 as *mut i32;
pub const fpu_ip_selector: *mut i32 = 1052 as *mut i32;
pub const fpu_dp: *mut i32 = 1056 as *mut i32;
pub const fpu_dp_selector: *mut i32 = 1060 as *mut i32;
pub const tss_size_32: *mut bool = 1128 as *mut bool;
pub const sse_scratch_register: *mut reg128 = 1136 as *mut reg128;
pub const fpu_st: *mut F80 = 1152 as *mut F80;
/// f64 shadow of the physical x87 registers (cpu::fpu), with VALID/DIRTY
/// masks, at fixed addresses so natively generated IR fixtures stay valid.
pub const x87_shadow_values: *mut [u64; 8] = 1280 as *mut [u64; 8];
pub const x87_shadow_valid: *mut u32 = 1344 as *mut u32;
pub const x87_shadow_dirty: *mut u32 = 1348 as *mut u32;
/// Nonzero while generated IR code may inline fast-math x87 on that cache.
pub const x87_native_policy: *mut u8 = 1352 as *mut u8;
pub const slice_budget: *mut u32 = 1356 as *mut u32;
pub const x64_gpr_hi: *mut u32 = 1360 as *mut u32;
pub const x64_gpr_ext_lo: *mut u32 = 1424 as *mut u32;
pub const x64_xmm_ext: *mut reg128 = 1456 as *mut reg128;
pub const x64_rip_hi: *mut u32 = 1584 as *mut u32;
pub const x64_previous_ip_hi: *mut u32 = 1588 as *mut u32;
pub const x64_idtr_base_hi: *mut u32 = 1592 as *mut u32;
pub const x64_gdtr_base_hi: *mut u32 = 1596 as *mut u32;
pub const x64_cr_hi: *mut u32 = 1600 as *mut u32;
pub const x64_dr_hi: *mut u32 = 1632 as *mut u32;
pub const x64_segment_base_hi: *mut u32 = 1664 as *mut u32;
pub const x64_efer: *mut u64 = 1696 as *mut u64;
pub const x64_kernel_gs_base: *mut u64 = 1704 as *mut u64;
pub const x64_star: *mut u64 = 1712 as *mut u64;
pub const x64_lstar: *mut u64 = 1720 as *mut u64;
pub const x64_cstar: *mut u64 = 1728 as *mut u64;
pub const x64_sfmask: *mut u64 = 1736 as *mut u64;
pub const x64_cs_long: *mut u8 = 1744 as *mut u8;
pub const x64_rex: *mut u8 = 1748 as *mut u8;
pub const x64_cr8: *mut u64 = 1752 as *mut u64;
pub const x64_sysenter_esp_hi: *mut u32 = 1760 as *mut u32;
pub const x64_sysenter_eip_hi: *mut u32 = 1764 as *mut u32;
pub const x64_fpu_ip_hi: *mut u32 = 1768 as *mut u32;
pub const x64_fpu_dp_hi: *mut u32 = 1772 as *mut u32;
pub const x64_pat: *mut u64 = 1776 as *mut u64;
pub const x64_tsc_aux: *mut u32 = 1784 as *mut u32;
pub const x64_page_exit: *mut u32 = 1792 as *mut u32;
pub const x64_jac_base: *mut u32 = 1796 as *mut u32;
pub const x64_jac_epoch: *mut u64 = 1800 as *mut u64;
pub const x64_page_linear: *mut u64 = 1808 as *mut u64;
/// Address of cpu::tlb_data, written at startup. Generated IR code loads it
/// from this fixed slot (below --global-base) instead of calling an import.
pub const ir_tlb_base: *mut u32 = 2048 as *mut u32;
pub const x64_mtrr_def_type: *mut u64 = 2056 as *mut u64;
pub const x64_mtrr_fixed: *mut u64 = 2064 as *mut u64;
pub const x64_mtrr_var: *mut u64 = 2152 as *mut u64;
pub const x64_mcg_status: *mut u64 = 2280 as *mut u64;
pub const x64_mcg_ctl: *mut u64 = 2288 as *mut u64;
pub const x64_mc_banks: *mut u64 = 2296 as *mut u64;
// END GENERATED

pub fn get_reg32_offset(r: u32) -> u32 {
    dbg_assert!(r < 8);
    (unsafe { reg32.offset(r as isize) }) as u32
}

pub fn get_reg_mmx_offset(r: u32) -> u32 {
    dbg_assert!(r < 8);
    (unsafe { fpu_st.offset(r as isize) }) as u32
}

pub fn get_reg_xmm_offset(r: u32) -> u32 {
    dbg_assert!(r < 8);
    (unsafe { reg_xmm.offset(r as isize) }) as u32
}

pub fn get_sreg_offset(s: u32) -> u32 {
    dbg_assert!(s < 6);
    (unsafe { sreg.offset(s as isize) }) as u32
}

pub fn get_seg_offset(s: u32) -> u32 {
    dbg_assert!(s < 8);
    (unsafe { segment_offsets.offset(s as isize) }) as u32
}

pub fn get_segment_is_null_offset(s: u32) -> u32 {
    dbg_assert!(s < 8);
    (unsafe { segment_is_null.offset(s as isize) }) as u32
}

pub fn get_creg_offset(i: u32) -> u32 {
    dbg_assert!(i < 8);
    (unsafe { cr.offset(i as isize) }) as u32
}
