#![allow(non_upper_case_globals)]

use crate::cpu::cpu::reg128;
use crate::softfloat::F80;
use crate::state_flags::CachedStateFlags;

/// The CPU state of this instance. The default build keeps it at fixed
/// addresses below --global-base (4096), which generated code reads directly.
/// The parallel build (docs/multicore.md) places
/// it in a static instead: every vCPU worker relocates its own copy of the
/// module into the shared memory, and with it this block; generated code of a
/// worker embeds that worker's addresses. Offsets are the same in both.
#[cfg(feature = "parallel")]
#[repr(C, align(64))]
pub struct StateBlock(pub [u8; 4096]);
#[cfg(feature = "parallel")]
pub static mut STATE_BLOCK: StateBlock = StateBlock([0; 4096]);

macro_rules! state {
    ($name:ident: $type:ty = $offset:literal) => {
        #[cfg(not(feature = "parallel"))]
        pub const $name: *mut $type = $offset as *mut $type;
        #[cfg(feature = "parallel")]
        pub const $name: *mut $type = unsafe {
            (&raw mut STATE_BLOCK)
                .cast::<u8>()
                .add($offset)
                .cast::<$type>()
        };
    };
}

/// Address of offset 0 of the state layout (src/state_layout.js)
#[no_mangle]
pub fn state_base() -> u32 {
    #[cfg(feature = "parallel")]
    return (&raw mut STATE_BLOCK) as u32;
    #[cfg(not(feature = "parallel"))]
    return 0;
}

// BEGIN GENERATED by gen/state_layout.js (edit the layout there)
state!(reg8: u8 = 64);
state!(reg16: u16 = 64);
state!(reg32: i32 = 64);
state!(last_op_size: i32 = 96);
state!(flags_changed: i32 = 100);
state!(last_op1: i32 = 104);
state!(state_flags: CachedStateFlags = 108);
state!(last_result: i32 = 112);
state!(flags: i32 = 120);
state!(segment_access_bytes: u8 = 512); // TODO: reorder below segment_limits
state!(apic_enabled: bool = 548);
state!(acpi_enabled: bool = 552);
state!(instruction_pointer: i32 = 556);
state!(previous_ip: i32 = 560);
state!(idtr_size: i32 = 564);
state!(idtr_offset: i32 = 568);
state!(gdtr_size: i32 = 572);
state!(gdtr_offset: i32 = 576);
state!(cr: i32 = 580);
state!(cpl: u8 = 612);
state!(in_hlt: bool = 616);
state!(last_virt_eip: i32 = 620);
state!(eip_phys: i32 = 624);
state!(nmi_blocked: bool = 628);
state!(interrupt_shadow: u8 = 632);
state!(sysenter_cs: i32 = 636);
state!(sysenter_esp: i32 = 640);
state!(sysenter_eip: i32 = 644);
state!(prefixes: u8 = 648);
state!(instruction_counter: u32 = 664);
state!(sreg: u16 = 668);
state!(dreg: i32 = 684);
state!(svga_dirty_bitmap_min_offset: u32 = 716); // filled in by svga_fill_pixel_buffer, read by javacsript for optimised putImageData calls
state!(svga_dirty_bitmap_max_offset: u32 = 720);
state!(segment_is_null: bool = 724);
state!(segment_offsets: i32 = 736);
state!(segment_limits: u32 = 768);
state!(protected_mode: bool = 800);
state!(is_32: bool = 804);
state!(stack_size_32: bool = 808);
state!(memory_size: u32 = 812);
state!(fpu_stack_empty: u8 = 816);
state!(mxcsr: i32 = 824);
state!(reg_xmm: reg128 = 832);
state!(current_tsc: u64 = 960);
state!(reg_pdpte: u64 = 968); // 4 64-bit entries
state!(fpu_stack_ptr: u8 = 1032);
state!(fpu_control_word: u16 = 1036);
state!(fpu_status_word: u16 = 1040);
state!(fpu_opcode: i32 = 1044);
state!(fpu_ip: i32 = 1048);
state!(fpu_ip_selector: i32 = 1052);
state!(fpu_dp: i32 = 1056);
state!(fpu_dp_selector: i32 = 1060);
state!(tss_size_32: bool = 1128);
state!(sse_scratch_register: reg128 = 1136);
state!(fpu_st: F80 = 1152);
// f64 shadow of the physical x87 registers (cpu::fpu), with VALID/DIRTY
// masks, at fixed addresses so natively generated IR fixtures stay valid.
state!(x87_shadow_values: [u64; 8] = 1280);
state!(x87_shadow_valid: u32 = 1344);
state!(x87_shadow_dirty: u32 = 1348);
// Nonzero while generated IR code may inline fast-math x87 on that cache.
state!(x87_native_policy: u8 = 1352);
state!(slice_budget: u32 = 1356);
state!(x64_gpr_hi: u32 = 1360);
state!(x64_gpr_ext_lo: u32 = 1424);
state!(x64_xmm_ext: reg128 = 1456);
state!(x64_rip_hi: u32 = 1584);
state!(x64_previous_ip_hi: u32 = 1588);
state!(x64_idtr_base_hi: u32 = 1592);
state!(x64_gdtr_base_hi: u32 = 1596);
state!(x64_cr_hi: u32 = 1600);
state!(x64_dr_hi: u32 = 1632);
state!(x64_segment_base_hi: u32 = 1664);
state!(x64_efer: u64 = 1696);
state!(x64_kernel_gs_base: u64 = 1704);
state!(x64_star: u64 = 1712);
state!(x64_lstar: u64 = 1720);
state!(x64_cstar: u64 = 1728);
state!(x64_sfmask: u64 = 1736);
state!(x64_cs_long: u8 = 1744);
state!(x64_rex: u8 = 1748);
state!(x64_cr8: u64 = 1752);
state!(x64_sysenter_esp_hi: u32 = 1760);
state!(x64_sysenter_eip_hi: u32 = 1764);
state!(x64_fpu_ip_hi: u32 = 1768);
state!(x64_fpu_dp_hi: u32 = 1772);
state!(x64_pat: u64 = 1776);
state!(x64_tsc_aux: u32 = 1784);
state!(x64_page_exit: u32 = 1792);
state!(x64_jac_base: u32 = 1796);
state!(x64_jac_epoch: u64 = 1800);
state!(x64_page_linear: u64 = 1808);
state!(x64_page_chain: u32 = 1816);
state!(x64_code_base: u32 = 1820);
state!(x64_page_lazy_kind: u32 = 1824);
state!(x64_page_lazy_a: u64 = 1832);
state!(x64_page_lazy_b: u64 = 1840);
state!(smm_state: u32 = 1856);
state!(smbase: u32 = 1860);
state!(x64_chain_gprs: u64 = 1864);
// Address of cpu::tlb_data, written at startup. Generated IR code loads it
// from this fixed slot (below --global-base) instead of calling an import.
state!(ir_tlb_base: u32 = 2048);
state!(x64_mtrr_def_type: u64 = 2056);
state!(x64_mtrr_fixed: u64 = 2064);
state!(x64_mtrr_var: u64 = 2152);
state!(x64_mcg_status: u64 = 2280);
state!(x64_mcg_ctl: u64 = 2288);
state!(x64_mc_banks: u64 = 2296);
state!(xcr0: u64 = 2432);
state!(xss: u64 = 2440);
state!(ymm_hi: reg128 = 2448);
// END GENERATED

pub fn get_reg32_offset(r: u32) -> u32 {
    dbg_assert!(r < 8);
    (unsafe { reg32.offset(r as isize) }) as u32
}

pub fn get_reg_mmx_offset(r: u32) -> u32 {
    dbg_assert!(r < 8);
    (unsafe { fpu_st.offset(r as isize) }) as u32
}

pub fn get_reg_xmm_offset(r: u32) -> u32 {
    dbg_assert!(r < 8);
    (unsafe { reg_xmm.offset(r as isize) }) as u32
}

pub fn get_sreg_offset(s: u32) -> u32 {
    dbg_assert!(s < 6);
    (unsafe { sreg.offset(s as isize) }) as u32
}

pub fn get_seg_offset(s: u32) -> u32 {
    dbg_assert!(s < 8);
    (unsafe { segment_offsets.offset(s as isize) }) as u32
}

pub fn get_segment_is_null_offset(s: u32) -> u32 {
    dbg_assert!(s < 8);
    (unsafe { segment_is_null.offset(s as isize) }) as u32
}

pub fn get_creg_offset(i: u32) -> u32 {
    dbg_assert!(i < 8);
    (unsafe { cr.offset(i as isize) }) as u32
}
