#!/usr/bin/env node

// The Venus wire format of src/graphics_adapters/virtio_gpu/venus_protocol.js
// (generated by tools/venus_protocol_gen.mjs from Mesa's C) against Mesa's
// own code: venus_protocol_vectors.txt holds requests Mesa's encoders wrote
// (tools/venus_oracle/oracle.c), which must decode to what they were made
// of and encode again (tests/devices/venus_guest_protocol.js) to the same
// bytes; and replies this encoder wrote, with what Mesa's decoders read
// from them, which must still come out the same.

import assert from "assert/strict";
import fs from "node:fs";
import url from "node:url";

const __dirname = url.fileURLToPath(new URL(".", import.meta.url));
const P = await import("../../src/graphics_adapters/virtio_gpu/venus_protocol.js");
const { GUEST } = await import("./venus_guest_protocol.js");

const vectors = { request: {}, reply: {}, mesa: {} };
for(const line of fs.readFileSync(__dirname + "/venus_protocol_vectors.txt", "utf8").split("\n"))
{
    if(!line || line.startsWith("#")) continue;
    const [kind, name, ...rest] = line.split(" ");
    vectors[kind][name] = rest.join(" ");
}
const unhex = hex => Uint8Array.from(hex.match(/../g), h => parseInt(h, 16));
const hex = bytes => Array.from(bytes, b => b.toString(16).padStart(2, "0")).join("");
const by_name = {};
for(const [type, entry] of Object.entries(P.COMMANDS)) by_name[entry[0]] = [+type, entry[1], entry[2]];

/** a request: its type, flags, decoded parameters */
const decode = name => {
    const bytes = unhex(vectors.request[name]);
    const r = new P.VenusReader(bytes);
    const type = r.u32(), flags = r.u32();
    const a = by_name[name][1](r);
    assert.equal(type, by_name[name][0], name + ": its command type");
    assert.equal(r.p, bytes.length, name + ": all of it read");
    a.cmd_flags = flags;
    return a;
};

// Every request decodes and encodes again to Mesa's bytes
for(const name of Object.keys(vectors.request))
{
    const a = decode(name);
    // (an output the request only sizes)
    if(name === "vkGetQueryPoolResults") a.pData = new Uint8Array(a.dataSize);
    const w = new P.VenusWriter(16);
    GUEST[name][0](w, a);
    assert.equal(hex(w.result()), vectors.request[name], name + ": encoded again");
}
console.log("PASS: " + Object.keys(vectors.request).length + " requests of Mesa's encoders, decoded and encoded again");

// What they decode to
let a = decode("vkCreateInstance");
assert.deepEqual(a.pCreateInfo.ppEnabledExtensionNames, ["VK_KHR_surface", "VK_EXT_debug_utils"]);
assert.equal(a.pCreateInfo.pApplicationInfo.pApplicationName, "vktest");
assert.equal(a.pCreateInfo.pApplicationInfo.pEngineName, null);
assert.equal(a.pInstance, 0x1234);
a = decode("vkCreateDevice");
assert.equal(a.pCreateInfo.pNext.sType, 1000059000, "VkPhysicalDeviceFeatures2 in the chain");
assert.equal(a.pCreateInfo.pNext.features.samplerAnisotropy, 1);
assert.equal(a.pCreateInfo.pNext.pNext.timelineSemaphore, 1, "VkPhysicalDeviceVulkan12Features after it");
assert.deepEqual(Array.from(a.pCreateInfo.pQueueCreateInfos[0].pQueuePriorities), [1, 0.5]);
a = decode("vkCreateBuffer");
assert.equal(a.pCreateInfo.size, 0x100000005, "64-bit sizes");
assert.deepEqual(Array.from(a.pCreateInfo.pQueueFamilyIndices), [0, 3], "concurrent sharing's families");
a = decode("vkUpdateDescriptorSets");
assert.equal(a.pDescriptorWrites[0].pImageInfo[1].imageView, 0x63);
assert.equal(a.pDescriptorWrites[1].pBufferInfo[0].range, 2 ** 64, "VK_WHOLE_SIZE");
a = decode("vkCmdBeginRenderPass");
assert.deepEqual(Array.from(new Float32Array(a.pRenderPassBegin.pClearValues[0].color.uint32.buffer)), [0.25, 0.5, 0.75, 1],
    "clear values: their bits");
a = decode("vkCreateGraphicsPipelines");
const pipeline = a.pCreateInfos[0];
assert.equal(pipeline.pStages[1].pName, "fs_main");
assert.deepEqual(Array.from(pipeline.pStages[1].pSpecializationInfo.pData), [7, 0, 0, 0, 9, 0, 0, 0]);
assert.deepEqual(Array.from(pipeline.pMultisampleState.pSampleMask), [15]);
assert.equal(pipeline.basePipelineIndex, -1);
a = decode("vkCmdDrawMultiEXT");
assert.deepEqual(a.pVertexInfo, [{ firstVertex: 3, vertexCount: 6 }, { firstVertex: 10, vertexCount: 4 }], "a strided array");
a = decode("vkCreateRingMESA");
assert.equal(a.ring, 0x7f0012345678);
assert.equal(a.pCreateInfo.pNext.maxReportingPeriodMicroseconds, 3000000);
console.log("PASS: what they decode to");

// Replies: the same objects encode to the bytes Mesa's decoders read
const replies = {
    "vkEnumeratePhysicalDevices": () => ({ ...decode("vkEnumeratePhysicalDevices"), ret: 0 }),
    "vkGetPhysicalDeviceProperties2": () => {
        const a = decode("vkGetPhysicalDeviceProperties2");
        a.pProperties.properties = { apiVersion: 0x403000, vendorID: 0x1af4, deviceName: "v86 WebGPU (Venus)", deviceType: 4,
            pipelineCacheUUID: [9, 8, 7], limits: { maxImageDimension2D: 8192, pointSizeRange: [1, 64] } };
        const driver = a.pProperties.pNext, v11 = driver.pNext;
        Object.assign(driver, { driverID: 22, driverName: "v86", conformanceVersion: { major: 1, minor: 3 } });
        Object.assign(v11, { deviceUUID: Array.from({ length: 16 }, (_, i) => i + 100), subgroupSize: 32, maxMultiviewViewCount: 6 });
        return a;
    },
    "vkGetPhysicalDeviceMemoryProperties": () => ({ pMemoryProperties: { memoryTypeCount: 2,
        memoryTypes: [{ propertyFlags: 1, heapIndex: 0 }, { propertyFlags: 0xE, heapIndex: 0 }], memoryHeapCount: 1,
        memoryHeaps: [{ size: 0x100000000, flags: 1 }] } }),
    "vkCreateBuffer": () => ({ ...decode("vkCreateBuffer"), ret: 0 }),
    "vkEnumerateInstanceExtensionProperties": () => ({ ret: 0, pPropertyCount: 2,
        pProperties: [{ extensionName: "VK_KHR_surface", specVersion: 25 }, { extensionName: "VK_EXT_debug_utils", specVersion: 2 }] }),
    "vkGetQueryPoolResults": () => ({ ...decode("vkGetQueryPoolResults"), ret: 0,
        pData: new Uint8Array(new BigUint64Array([1n, 0x1122334455667788n, 3n, 4n]).buffer) }),
    "vkGetBufferDeviceAddress": () => ({ ret: 0x7f0000001000 }),
    "vkGetPhysicalDeviceQueueFamilyProperties2": () => {
        const a = decode("vkGetPhysicalDeviceQueueFamilyProperties2");
        a.pQueueFamilyPropertyCount = 1;
        a.pQueueFamilyProperties.length = 1;
        a.pQueueFamilyProperties[0].queueFamilyProperties = { queueFlags: 7, queueCount: 1, timestampValidBits: 64,
            minImageTransferGranularity: { width: 1, height: 1, depth: 1 } };
        return a;
    },
};
for(const [name, make] of Object.entries(replies))
{
    assert.ok(vectors.mesa[name].includes("fatal=0 left=0"), name + ": Mesa read it all, without errors");
    const w = new P.VenusWriter(16);
    by_name[name][2](w, make());
    assert.equal(hex(w.result()), vectors.reply[name], name + ": the reply Mesa read");
}
// and the driver's side reads them as Mesa did
let reply = GUEST["vkGetPhysicalDeviceProperties2"][1](new P.VenusReader(unhex(vectors.reply["vkGetPhysicalDeviceProperties2"])));
assert.equal(reply.pProperties.properties.deviceName, "v86 WebGPU (Venus)");
assert.equal(reply.pProperties.pNext.driverName, "v86");
assert.equal(reply.pProperties.pNext.pNext.maxMultiviewViewCount, 6);
assert.match(vectors.mesa["vkGetPhysicalDeviceProperties2"], /name=v86 WebGPU \(Venus\) .* driverName=v86 .* maxMultiviewViewCount=6/);
reply = GUEST["vkGetQueryPoolResults"][1](new P.VenusReader(unhex(vectors.reply["vkGetQueryPoolResults"])));
assert.deepEqual(Array.from(new BigUint64Array(reply.pData.buffer)), [1n, 0x1122334455667788n, 3n, 4n]);
console.log("PASS: " + Object.keys(replies).length + " replies, as Mesa's decoders read them");
