#!/usr/bin/env node
// Generate src/graphics_adapters/vmware_svga/svga_formats.js from
// third_party/vmware-svga/svga3d_surfacedefs.h: for every SVGA3dSurfaceFormat
// its block description (SVGA3DBLOCKDESC_* bits), block size in texels and
// bytes per block, which give the layout of surfaces in MOBs and the formats
// GX picks for WebGPU. Run after updating the headers.
//
//     node tools/gen_svga_formats.js

import fs from "node:fs";
import path from "node:path";
import url from "node:url";

const ROOT = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), "..");
const HEADER = path.join(ROOT, "third_party/vmware-svga/svga3d_surfacedefs.h");
const OUTPUT = path.join(ROOT, "src/graphics_adapters/vmware_svga/svga_formats.js");
const C = await import(url.pathToFileURL(path.join(ROOT, "src/graphics_adapters/vmware_svga/svga_constants.js")));

const text = fs.readFileSync(HEADER, "utf8").replace(/\/\*[\s\S]*?\*\//g, " ").replace(/\/\/.*$/gm, " ");

// enum SVGA3dBlockDesc: each name's value, from earlier ones
const blockdesc = new Map();
const enum_body = text.match(/typedef enum SVGA3dBlockDesc \{([\s\S]*?)\} SVGA3dBlockDesc;/)[1];
for(const item of enum_body.split(","))
{
    const m = item.match(/^\s*(SVGA3DBLOCKDESC_\w+)\s*=\s*([\s\S]+?)\s*$/);
    if(!m) continue;
    const expression = m[2].replace(/SVGA3DBLOCKDESC_\w+/g, name => {
        if(!blockdesc.has(name)) throw new Error("unknown " + name);
        return String(blockdesc.get(name));
    });
    blockdesc.set(m[1], Function("return (" + expression + ") >>> 0")());
}

// the table: {format, blockdesc, {w, h, d}, bytes, pitch bytes, ...}
const table = text.match(/g_SVGA3dSurfaceDescs\[SVGA3D_FORMAT_MAX\] = \{([\s\S]*?)\n\};/)[1];
const entries = [];
const re = /\{\s*(SVGA3D_\w+),\s*(SVGA3DBLOCKDESC_\w+),\s*\{(\d+),\s*(\d+),\s*(\d+)\},\s*(\d+),\s*(\d+),\s*\{\{(\d+)\},\s*\{(\d+)\},\s*\{(\d+)\},\s*\{(\d+)\}\}/g;
for(let m; (m = re.exec(table));)
{
    const format = C[m[1]];
    if(format === undefined) throw new Error("unknown format " + m[1]);
    entries[format] = [m[1], blockdesc.get(m[2]), +m[3], +m[4], +m[5], +m[6], +m[7], [+m[8], +m[9], +m[10], +m[11]]];
}
if(entries.length !== C.SVGA3D_FORMAT_MAX) throw new Error("expected " + C.SVGA3D_FORMAT_MAX + " formats, got " + entries.length);

let out = `// Generated by tools/gen_svga_formats.js from third_party/vmware-svga/svga3d_surfacedefs.h
// (VMware SVGA3D, GPL-2.0 OR MIT, used under MIT). Do not edit.

`;
for(const [name, value] of blockdesc) out += `export const ${name} = 0x${value.toString(16).toUpperCase()};\n`;
out += `
/**
 * For each SVGA3dSurfaceFormat: [SVGA3DBLOCKDESC_* bits, block width,
 * height and depth in texels, bytes per block, bytes per block in a pitch,
 * bits of the R, G, B, A channels (or of the depth, stencil ones)]
 * @type {!Array<!Array<(number|!Array<number>)>>}
 */
export const SURFACE_DESCS = [
`;
for(const [name, desc, w, h, d, bytes, pitch, bits] of entries)
{
    out += `    [0x${desc.toString(16)}, ${w}, ${h}, ${d}, ${bytes}, ${pitch}, [${bits.join(", ")}]], // ${name}\n`;
}
out += "];\n";
fs.writeFileSync(OUTPUT, out);
console.log("wrote " + path.relative(ROOT, OUTPUT) + ": " + entries.length + " formats, " + blockdesc.size + " block descriptions");
