// Generated by gen/cpu_features.js from its feature table; do not edit.

/**
 * The CPU features of docs/simd-xsave-plan.md: bit in the machine's set
 * (src/rust/cpu/features.rs), required features, the lowest cpuid_level that
 * reports it, the CPU profiles that may have it and whether its milestone is
 * released (else it is for tests and development)
 */
export const CPU_FEATURES = {
    "SSSE3": {
        "bit": 0,
        "requires": [],
        "min_cpuid_level": 1,
        "profiles": [
            "x86",
            "x86_64"
        ],
        "released": true
    },
    "SSE4.1": {
        "bit": 1,
        "requires": [
            "SSSE3"
        ],
        "min_cpuid_level": 1,
        "profiles": [
            "x86",
            "x86_64"
        ],
        "released": true
    },
    "SSE4.2": {
        "bit": 2,
        "requires": [
            "SSE4.1"
        ],
        "min_cpuid_level": 1,
        "profiles": [
            "x86",
            "x86_64"
        ],
        "released": true
    },
    "XSAVE": {
        "bit": 3,
        "requires": [],
        "min_cpuid_level": 13,
        "profiles": [
            "x86",
            "x86_64"
        ],
        "released": true
    },
    "AVX": {
        "bit": 4,
        "requires": [
            "XSAVE",
            "SSE4.2"
        ],
        "min_cpuid_level": 1,
        "profiles": [
            "x86",
            "x86_64"
        ],
        "released": true
    },
    "AVX2": {
        "bit": 5,
        "requires": [
            "AVX"
        ],
        "min_cpuid_level": 7,
        "profiles": [
            "x86",
            "x86_64"
        ],
        "released": false
    },
    "FMA": {
        "bit": 6,
        "requires": [
            "AVX"
        ],
        "min_cpuid_level": 1,
        "profiles": [
            "x86",
            "x86_64"
        ],
        "released": false
    },
    "F16C": {
        "bit": 7,
        "requires": [
            "AVX"
        ],
        "min_cpuid_level": 1,
        "profiles": [
            "x86",
            "x86_64"
        ],
        "released": false
    },
    "BMI1": {
        "bit": 8,
        "requires": [],
        "min_cpuid_level": 7,
        "profiles": [
            "x86",
            "x86_64"
        ],
        "released": false
    },
    "BMI2": {
        "bit": 9,
        "requires": [],
        "min_cpuid_level": 7,
        "profiles": [
            "x86",
            "x86_64"
        ],
        "released": false
    },
    "LZCNT": {
        "bit": 10,
        "requires": [],
        "min_cpuid_level": 1,
        "profiles": [
            "x86_64"
        ],
        "released": false
    },
    "MOVBE": {
        "bit": 11,
        "requires": [],
        "min_cpuid_level": 1,
        "profiles": [
            "x86",
            "x86_64"
        ],
        "released": false
    },
    "XSAVEOPT": {
        "bit": 12,
        "requires": [
            "XSAVE"
        ],
        "min_cpuid_level": 13,
        "profiles": [
            "x86",
            "x86_64"
        ],
        "released": false
    },
    "XSAVEC": {
        "bit": 13,
        "requires": [
            "XSAVE"
        ],
        "min_cpuid_level": 13,
        "profiles": [
            "x86",
            "x86_64"
        ],
        "released": false
    },
    "XGETBV1": {
        "bit": 14,
        "requires": [
            "XSAVE"
        ],
        "min_cpuid_level": 13,
        "profiles": [
            "x86",
            "x86_64"
        ],
        "released": false
    },
    "XSAVES": {
        "bit": 15,
        "requires": [
            "XSAVEC"
        ],
        "min_cpuid_level": 13,
        "profiles": [
            "x86",
            "x86_64"
        ],
        "released": false
    }
};

/** Feature sets by name */
export const CPU_FEATURE_PRESETS = {
    "x86-64-v2": [
        "SSSE3",
        "SSE4.1",
        "SSE4.2"
    ],
    "x86-64-v3": [
        "SSSE3",
        "SSE4.1",
        "SSE4.2",
        "XSAVE",
        "AVX",
        "AVX2",
        "FMA",
        "F16C",
        "BMI1",
        "BMI2",
        "LZCNT",
        "MOVBE"
    ]
};
